#!/bin/sh /etc/rc.common

USE_PROCD=1
START=20
STOP=89

start_service() {
    [ -x /usr/sbin/fan-speed ] || return 1
    /usr/sbin/fan-speed setup

    procd_open_instance
    procd_set_param command /usr/sbin/fan-speed daemon
    procd_set_param respawn 3600 5 5
    procd_close_instance
}

stop_service() {
    [ -d /sys/class/pwm/pwmchip0/pwm1 ] || return 1
    echo 10000 > /sys/class/pwm/pwmchip0/pwm1/duty_cycle 2>/dev/null
}

reload_service() {
    stop_service
    start_service
}

service_triggers() {
    procd_add_reload_trigger luci-fan
}
